### ISSUE TITLE
Unexpected width value in .user-page .provider .favicon CSS width

### ISSUE THREAD

**Issue by pdehaan** [mozilla/chronicle#311]
In [/app/styles/modules/_user_page.scss:35](https://github.com/mozilla/chronicle/blob/408fdde81b084704b5c5c82c6f9506bda7b58d1e/app/styles/modules/_user_page.scss#L35) we have the following code:
```scss
    .favicon {
      height: $half-grid;
      margin-right: 5px;
      vertical-align: -3px;
      width: 1$half-grid; /* <---- this guy! */
    }
```

Which compiles to this [de-minified] code:
```css
    .user-page .provider .favicon {
      height: 16px;
      margin-right: 5px;
      vertical-align: -3px;
      width: 1 16px; /* <---- this guy! */
    }
```

CSSLint blows up with this hawkward error:
> _**WARNING:** Expected end of value but found '16px'. Properties should be known (listed in CSS3 specification) or be a vendor-prefixed property. (known-properties) Browsers: All_
